### Register a new user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "Test@example.com",
  "password": "securepassword123"
}


### Login user
POST http://localhost:5000/auth/login

Content-Type: application/json

{
  "email": "Test@example.co",
  "password": "securepassword12"
}

